// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfmutkwfztndsbrqwjit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmbXV0a3dmenRuZHNicnF3aml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyODQ1NDAsImV4cCI6MjA5MDg2MDU0MH0.1O7iOPG9XWoSg6-pwiFDuHjSJNN8Qx2G9p6yoRsSfLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});